import React,{useEffect,useMemo,useState} from 'react';
import {CheckCircle2,FileCheck2,Plus,RefreshCw,ShieldCheck,Trash2} from 'lucide-react';
import {supabase} from '../firebase';

type Row={id:number;unit_id:string;unit_name:string;medicine_id:string;medicine_name:string;quantity:number;opening_batch_no:string;provenance_status:'unknown'|'documented'|'verified';evidence_note:string;lines:any[]};
type Line={batchNo:string;expDate:string;source:string;price:string;quantity:string;evidenceNote:string};
const empty=():Line=>({batchNo:'',expDate:'',source:'DAK',price:'',quantity:'',evidenceNote:''});
export default function OpeningReconciliationView({onNotify}:{onNotify?:(t:'success'|'error'|'warning'|'info',m:string)=>void}){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Row|null>(null),[lines,setLines]=useState<Line[]>([empty()]),[busy,setBusy]=useState(false),[filter,setFilter]=useState<'pending'|'verified'|'all'>('pending');
 const load=async()=>{setLoading(true);const {data,error}=await supabase.rpc('list_legacy_opening_reconciliations');setLoading(false);if(error){onNotify?.('error',error.message);return;}setRows((data||[]) as Row[]);};
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>rows.filter(r=>filter==='all'||(filter==='verified'?r.provenance_status==='verified':r.provenance_status!=='verified')),[rows,filter]);
 const open=(r:Row)=>{setSelected(r);setLines(r.lines?.length?r.lines.map((x:any)=>({batchNo:x.batchNo,expDate:x.expDate,source:x.source,price:x.price==null?'':String(x.price),quantity:String(x.quantity),evidenceNote:x.evidenceNote})):[empty()]);};
 const total=lines.reduce((n,x)=>n+(Number(x.quantity)||0),0);
 const save=async()=>{if(!selected)return;setBusy(true);const payload=lines.map(x=>({...x,price:x.price===''?null:Number(x.price),quantity:Number(x.quantity)}));const {error}=await supabase.rpc('save_legacy_opening_documentation',{p_reconciliation_id:selected.id,p_lines:payload});setBusy(false);if(error){onNotify?.('error',error.message);return;}onNotify?.('success','Dokumentasi opening stock tersimpan dan menunggu verifikasi.');await load();setSelected(null);};
 const verify=async(r:Row)=>{if(!confirm(`Verifikasi provenance ${r.medicine_name} di ${r.unit_name}? Total stok tidak akan diubah.`))return;setBusy(true);const {error}=await supabase.rpc('verify_legacy_opening_atomic',{p_reconciliation_id:r.id});setBusy(false);if(error){onNotify?.('error',error.message);return;}onNotify?.('success','Verifikasi APJ selesai atomik. Opening sentinel telah diganti provenance sebenarnya.');await load();};
 return <div className="space-y-5">
  <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3"><div><h2 className="text-xl md:text-2xl font-bold text-slate-800">Rekonsiliasi Opening Stock</h2><p className="text-xs text-slate-500">Lengkapi batch, ED, sumber dana dan harga dari bukti fisik. Verifikasi tidak mengubah total stok.</p></div><button onClick={load} className="inline-flex items-center justify-center gap-2 border border-slate-200 bg-white rounded-xl px-3 py-2 text-xs font-bold"><RefreshCw className="w-4 h-4"/>Muat ulang</button></div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['UNKNOWN',rows.filter(r=>r.provenance_status==='unknown').length],['Terdokumentasi',rows.filter(r=>r.provenance_status==='documented').length],['Terverifikasi',rows.filter(r=>r.provenance_status==='verified').length],['Total Opening',rows.reduce((n,r)=>n+Number(r.quantity),0)]].map(([a,b])=><div key={String(a)} className="bg-white border border-slate-200 rounded-xl p-3"><p className="text-[10px] font-bold uppercase text-slate-500">{a}</p><p className="text-xl font-black text-slate-800">{b}</p></div>)}</div>
  <div className="inline-flex bg-white border border-slate-200 rounded-xl p-1">{(['pending','verified','all'] as const).map(x=><button key={x} onClick={()=>setFilter(x)} className={`px-3 py-2 rounded-lg text-xs font-bold ${filter===x?'bg-teal-700 text-white':'text-slate-600'}`}>{x==='pending'?'Perlu Rekonsiliasi':x==='verified'?'Terverifikasi':'Semua'}</button>)}</div>
  <section className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="text-left p-3">Unit / Obat</th><th className="text-right p-3">Opening</th><th className="text-left p-3">Status</th><th className="text-right p-3">Aksi</th></tr></thead><tbody>{visible.map(r=><tr key={r.id} className="border-t border-slate-100"><td className="p-3"><b>{r.medicine_name}</b><p className="text-[10px] text-slate-500">{r.unit_name} • {r.opening_batch_no}</p></td><td className="p-3 text-right font-bold">{r.quantity}</td><td className="p-3"><span className={`rounded-full px-2 py-1 font-bold ${r.provenance_status==='verified'?'bg-emerald-50 text-emerald-700':r.provenance_status==='documented'?'bg-blue-50 text-blue-700':'bg-amber-50 text-amber-700'}`}>{r.provenance_status.toUpperCase()}</span></td><td className="p-3"><div className="flex justify-end gap-2">{r.provenance_status!=='verified'&&<button onClick={()=>open(r)} className="px-3 py-2 rounded-lg border border-slate-200 font-bold">{r.provenance_status==='documented'?'Edit Bukti':'Isi Bukti'}</button>}{r.provenance_status==='documented'&&<button disabled={busy} onClick={()=>verify(r)} className="inline-flex items-center gap-1 px-3 py-2 rounded-lg bg-emerald-600 text-white font-bold"><ShieldCheck className="w-4 h-4"/>Verifikasi APJ</button>}</div></td></tr>)}{!loading&&visible.length===0&&<tr><td colSpan={4} className="p-8 text-center text-slate-400">Tidak ada item.</td></tr>}</tbody></table></div></section>
  {selected&&<div className="fixed inset-0 z-[100] bg-slate-950/50 p-3 flex items-start sm:items-center justify-center overflow-y-auto"><div className="w-full max-w-4xl bg-white rounded-2xl shadow-xl p-4 sm:p-5 space-y-4 max-h-[calc(100dvh-1.5rem)] overflow-y-auto"><div><h3 className="font-bold text-slate-900">{selected.medicine_name} — {selected.unit_name}</h3><p className="text-xs text-slate-500">Opening {selected.quantity}. Total rincian harus sama persis.</p></div>{lines.map((l,i)=><div key={i} className="grid md:grid-cols-6 gap-2 p-3 bg-slate-50 rounded-xl"><input value={l.batchNo} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,batchNo:e.target.value}:x))} placeholder="No. batch" className="border rounded-lg p-2 text-xs"/><input type="date" value={l.expDate} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,expDate:e.target.value}:x))} className="border rounded-lg p-2 text-xs"/><select value={l.source} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,source:e.target.value}:x))} className="border rounded-lg p-2 text-xs">{['DAK','DAU','Program','JKN','PBF','Lainnya'].map(s=><option key={s}>{s}</option>)}</select><input type="number" value={l.price} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,price:e.target.value}:x))} placeholder="Harga" className="border rounded-lg p-2 text-xs"/><input type="number" value={l.quantity} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,quantity:e.target.value}:x))} placeholder="Jumlah" className="border rounded-lg p-2 text-xs"/><div className="flex gap-1"><input value={l.evidenceNote} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,evidenceNote:e.target.value}:x))} placeholder="Bukti: kartu stok/BAP..." className="min-w-0 flex-1 border rounded-lg p-2 text-xs"/><button onClick={()=>setLines(v=>v.filter((_,n)=>n!==i))} className="p-2 text-rose-600"><Trash2 className="w-4 h-4"/></button></div></div>)}<div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><button onClick={()=>setLines(v=>[...v,empty()])} className="inline-flex items-center gap-2 text-xs font-bold text-teal-700"><Plus className="w-4 h-4"/>Tambah batch</button><p className={`text-xs font-bold ${total===Number(selected.quantity)?'text-emerald-700':'text-rose-600'}`}>Total rincian {total} / {selected.quantity}</p></div><div className="flex justify-end gap-2"><button onClick={()=>setSelected(null)} className="px-4 py-2 text-xs font-bold">Batal</button><button disabled={busy||total!==Number(selected.quantity)} onClick={save} className="inline-flex items-center gap-2 bg-teal-700 disabled:bg-slate-300 text-white rounded-lg px-4 py-2 text-xs font-bold"><FileCheck2 className="w-4 h-4"/>Simpan Dokumentasi</button></div></div></div>}
 </div>
}