import React, { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle, Sparkles, XCircle } from 'lucide-react';
import { Medicine, PrescriptionItem, StockStore } from '../types';
import { SmartMatch, smartMatchPrescription } from '../utils/prescriptionSmartMatch';

type Props={text:string;medicines:Medicine[];stocks:StockStore;onApprove:(lines:PrescriptionItem[])=>void};
export default function PrescriptionSmartMatcher({text,medicines,stocks,onApprove}:Props){
 const initial=useMemo(()=>smartMatchPrescription(text,medicines,stocks),[text,medicines,stocks]);
 const [rows,setRows]=useState<SmartMatch[]>(initial); React.useEffect(()=>setRows(initial),[initial]);
 if(!text.trim())return null;
 const update=(i:number,p:Partial<SmartMatch>)=>setRows(v=>v.map((r,n)=>n===i?{...r,...p}:r));
 const approve=()=>{const safe=rows.filter(r=>r.medicineId&&r.qty>0&&r.qty<=r.available&&r.dosage!=='Perlu verifikasi aturan pakai');if(!safe.length)return;onApprove(safe.map(r=>({medicineId:r.medicineId!,qty:r.qty,dosage:r.dosage,isCompound:false})));};
 return <div className="rounded-2xl border border-indigo-100 bg-indigo-50/40 p-4 space-y-3"><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><Sparkles className="w-4 h-4 text-indigo-600 mt-0.5"/><div><div className="text-xs font-extrabold text-slate-800">Smart Matching Resep Excel → Master Obat</div><div className="text-[10px] text-slate-500">Hasil AI-rule matching wajib diverifikasi petugas sebelum masuk ke resep dan memotong stok.</div></div></div><span className="text-[10px] font-bold text-indigo-700">{rows.length} baris</span></div><div className="space-y-2">{rows.map((r,i)=><div key={i} className="rounded-xl border border-slate-200 bg-white p-3"><div className="text-[10px] text-slate-400 mb-2">Sumber: {r.sourceText}</div><div className="grid grid-cols-1 md:grid-cols-12 gap-2 items-end"><div className="md:col-span-5"><label className="text-[9px] font-bold text-slate-500 uppercase">Obat hasil cocok</label><select value={r.medicineId||''} onChange={e=>{const m=medicines.find(x=>x.id===e.target.value);update(i,{medicineId:m?.id,medicineName:m?.name,available:m?(stocks['ruang_farmasi']?.[m.id]?.total||0):0,status:m?'review':'unmatched'})}} className="w-full border rounded-lg px-2 py-2 text-xs bg-white"><option value="">— Belum cocok —</option>{medicines.filter(m=>(m.itemKind||'obat')==='obat').map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div><div className="md:col-span-2"><label className="text-[9px] font-bold text-slate-500 uppercase">Jumlah</label><input type="number" min="1" value={r.qty} onChange={e=>update(i,{qty:Number(e.target.value)||0})} className="w-full border rounded-lg px-2 py-2 text-xs"/></div><div className="md:col-span-3"><label className="text-[9px] font-bold text-slate-500 uppercase">Signa</label><input value={r.dosage} onChange={e=>update(i,{dosage:e.target.value})} className="w-full border rounded-lg px-2 py-2 text-xs"/></div><div className="md:col-span-2 text-xs"><div className={r.qty>r.available?'text-rose-600 font-bold':'text-emerald-700 font-bold'}>Stok {r.available.toLocaleString('id-ID')}</div><div className="text-[9px] text-slate-400">Cocok {Math.round(r.confidence*100)}%</div></div></div><div className="mt-2 flex items-center gap-1 text-[10px]">{!r.medicineId?<><XCircle className="w-3 h-3 text-rose-500"/><span className="text-rose-600">Perlu pilih obat</span></>:r.qty>r.available?<><AlertTriangle className="w-3 h-3 text-amber-500"/><span className="text-amber-700">Jumlah melebihi stok—tidak dapat disetujui</span></>:<><CheckCircle className="w-3 h-3 text-emerald-500"/><span className="text-emerald-700">Siap diverifikasi</span></>}</div></div>)}</div><div className="flex justify-end"><button type="button" onClick={approve} className="px-4 py-2 rounded-xl bg-indigo-600 text-white text-xs font-bold hover:bg-indigo-700"><CheckCircle className="w-3.5 h-3.5 inline mr-1"/>Verifikasi & Masukkan ke Draf Resep</button></div></div>;
}
